### ISSUE TITLE
Cannot find module 'aot-test-generators'

### ISSUE THREAD

**Issue by pichfl** [billybonks/broccoli-stylelint#104]
Happens in 2.1.0. 

It seems `aot-test-generators` should be in `dependencies` instead of a `devDependencies`, but I might be wrong.

**Comment by billybonks** [comment]
! thanks so much.

**Comment by billybonks** [comment]
sorry for the super delay on response

**Comment by ngsikai** [comment]
Closing this since it seems to be fixed
