### ISSUE TITLE
Can't find variable: module

### ISSUE THREAD

**Issue by eabait** [billybonks/broccoli-stylelint#3]
Hi!

I'm getting the following error:
```
TestLoader Failures <app-name>/tests/app.stylelint-test: could not be loaded
    ✘ Can't find variable: module
```
I think is because I'm using Mocha+Chai instead of QUnit. Is there a way to avoid this error?

EDIT: I've researched how other ember-cli addon works (ember-cli-eslint for instance), and found that you can rely on the project.generateTestFile method [see ember-cli-eslint](https://github.com/ember-cli/ember-cli-eslint/blob/master/index.js#L58)

Thanks!!
Esteban

**Comment by billybonks** [comment]
hey @eabait i only saw this issue now sorry. i presume you are using the `ember-cli-styelint` addon and not the broccoli plugin directly ?

**Comment by billybonks** [comment]
O actually sorry i wasn't thinking. yes i need to add support for qunit builds. for now you should be able to disable test generation with the option `generateTests:false`

**Comment by billybonks** [comment]
@eabait i updated the ember-cli plugin ember-cli-stylelint@0.2.0 👍  should work now

**Comment by eabait** [comment]
Thanks @billybonks !!
